### ISSUE TITLE
unzip those zip files to make online preview + git clone easier!

### ISSUE THREAD

**Issue by japhir** [bijlpeter83/RGDGT#1]
Hi Peter,

It'd be much easier to follow along if you could create a folder structure here that you just upload directly!
i.e.:
- `R/` (which has all your R scripts)
- `data/` or `data-raw/` (which has all the csv data)
- `vignettes/` or something similar for all the .Rmd files

If you really want people to easily try out your code, you might even [release it as an R package](https://r-pkgs.org/)

**Comment by bijlpeter83** [comment]
Thanks! I’ll look into it.

p

From: Ilja Kocken ***@***.***>
Date: Monday, 12 July 2021 at 17:44
To: bijlpeter83/RGDGT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bijlpeter83/RGDGT] unzip those zip files to make online preview + git clone easier! (#1)

Hi Peter,

It'd be much easier to follow along if you could create a folder structure here that you just upload directly!
i.e.:

  *   R/ (which has all your R scripts)
  *   data/ or data-raw/ (which has all the csv data)
  *   vignettes/ or something similar for all the .Rmd files

If you really want people to easily try out your code, you might even release it as an R package<https://r-pkgs.org/>

**Comment by japhir** [comment]
nicely done!
